### PR TITLE
Add an article from freeCodeCamp

### PR DESCRIPTION
**Pull request by amandeepmittal**
I wrote this back earlier this year. Hope it is still relevant. Thanks 🙏

### CODE REVIEW

**Comment by ooloth** [comment]
Nice article!

The build is failing because the title needs quotation marks around it because of the ":" in the middle of it. 

Once you make that quick change, I'll be happy to merge. 👍

Thanks for contributing!

**Comment by amandeepmittal** [comment]
Sorry about that!

**Comment by ooloth** [comment]
Oh yeah! Missed it the first time: the lines with `source:` and `topics:` (just those two) are indented one space too far.

**Comment by ooloth** [comment]
🎉

**Pull request merged**
